### PR TITLE
Use serve instead of http-server and include package-lock.json

### PR DESCRIPTION
**Pull request by SaschaSchwarze0**
It seems that a nested dependency of http-server changed and now this repository is broken. It fails when running `http-server -v`. I am switching to serve instead and include a package-lock.json to prevent hitting an issue with a breaking nested dependency update.

### CODE REVIEW

**Review by HeavyWombat — APPROVED** [review]
/lgtm

**Comment by SaschaSchwarze0** [comment]
Just noticed that I ran `npm install` with npm 8 while our base image contains npm 6. Repushed after run with npm 6 to get rid of the lockfile version mismatch.

**Review by sbose78 — APPROVED** [review]

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
